### PR TITLE
updated username dynamically

### PR DESCRIPTION
**Pull request by charitha-15**

### CODE REVIEW

**Review by shaikmoulana — APPROVED** [review]

**Review by Kedara17 — COMMENTED** [review]
Revied

**Comment by Kedara17** [comment]
submitted

**Review by Kedara17 — COMMENTED** [review]
Review

**Review by Kedara17 — COMMENTED** [review]
Update username dynamically

**Review by Kedara17 — COMMENTED** [review]
Need to review

**Review by Kedara17 — COMMENTED** [review]
need to review

**Pull request merged**
